apiVersion: ENC[AES256_GCM,data:Ry4=,iv:kMZ6PRIzOnSocIEi5uhjkShdbU/MwvZWx3hQ+RbDA7U=,tag:vnqsydhfkEr3TPxoxyqEnQ==,type:str]
kind: ENC[AES256_GCM,data:hnCvBG54,iv:92ODaNbocPwHYZbKxL5WntQkJdG+NL8S91gsAKaAHXc=,tag:hMTTE3IDedOv/R2613Z4AQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:HqmLa5y+0xYmblw0f2igeOg=,iv:hFs2LdEqEYB5FGoiedji2RZykdaCAcYpnMMsKomLo8g=,tag:sdlE6ax4HJcNXYZ5FdpC5w==,type:str]
    namespace: ENC[AES256_GCM,data:ezV7twU=,iv:m0m3FzIQkfcv2o6g624wm2KzTYm/A+1SFK2PJq2HmR8=,tag:bK/pubqdghpt3+59BfqYYA==,type:str]
type: ENC[AES256_GCM,data:4L0ynHCP,iv:CVy07440bMuYd1cGQuNUfWzYjm16FDa0wVCO3wthI9Q=,tag:dd/7FbbtOq//KfOaNp1+Eg==,type:str]
stringData:
    root-user: ENC[AES256_GCM,data:cXIeDCQ=,iv:GLBHtWS9vhsrIzJw9tq81pDcPgjekkr7tuvtnJA5liw=,tag:Q6Mk0pu8a2YXxmGOjv1t3Q==,type:str]
    root-password: ENC[AES256_GCM,data:9KzANxXxotQdlmdSOmA3dH0MqxZlIQsOeV4ev6o7CcY=,iv:VV/z4peDoUxWiw1PQVTH5Dj+y1DIDT8CohWYUOX8EmA=,tag:WtTMCZGpiR5p5tn8fsSOIQ==,type:str]
sops:
    age:
        - recipient: age18vt4yspgr9qtq30n6ty20l8jpxeu5drd38sl9kdlxqvggswtsdmsyeydck
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbmxETXNoR3I5cERGQldF
            TmVJSTlEM1cvUVBEOUZQZnZQdUJBbm94RldJCmRYMk1nZmY3anFVaFJEaEgwRHpk
            YXd0RStzR0xSVXRSNmRmUk5WVVdJUTgKLS0tIFJhUExZbFdaYnF5WGRDdFNvRUl3
            U01CTlVsOXNlVjdVaE9TU1VuVk9oekkKqmTRIKFlPG+AQBe71wn3x7us+aDYHv+e
            qsddVPDb4ubKxIlD/AjYKltUmszonkXKFbOUUD8K1KqgUSvmQBxCOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T13:52:25Z"
    mac: ENC[AES256_GCM,data:0rtdCRSGCrChodNPy4+ED2kw8xjIVx+MeLFEJjakz3uBORVoaLcVTvUrL90Dcn9227Qf0ckTIOtUQMya6qfdvxKrtTsdcWJYhe8JAOG/0SQmkKhqGiRij7nLYVZVGITiJ4Xud+uJq7HNeUej6g+56KxEuwbzIQgEi22R7fTDdFY=,iv:FFe+KTxk68fjDyP0EwKaPI3js5W0JWuI+lwnNTymdp8=,tag:wyPmdp+QrtlDTzxnHCcMEw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
