apiVersion: ENC[AES256_GCM,data:ZK8=,iv:loUHbwaASuJ2cc2z6Gb/Ote9ty4rgaAiuIfSLmyCjBg=,tag:qFkzhReaAq5SOFqzJPBiNg==,type:str]
kind: ENC[AES256_GCM,data:vPWXFFnd,iv:vJMDZy7gsbsaNFfMU6LesVf0j2xuJ/RX/dyuavFYnDs=,tag:A3/i6wS7Lno8A0XFtKNrEQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:1IWfDkrHmFTQSX0nPlLfdvfd,iv:ao91OMceVXr7NYIFBQtFTwjl8sdbR3B7OFx1M++fKNs=,tag:t4fm/X8C78yz2y8ZVx3UCA==,type:str]
    namespace: ENC[AES256_GCM,data:jL8gLWZ8,iv:yqPTlnlAQ62faClx7Mmqp+6QCdmDeWcK+CUMuBngd9w=,tag:v21PnKm8Xqa8tcYG60KSLA==,type:str]
type: ENC[AES256_GCM,data:TECb8mtc,iv:Sa5Ro8aIrUVXzNnD1crv5H7w41+uX2ng+s7JZFnMUUE=,tag:KJpWLzK9en337XrZnFV+rQ==,type:str]
stringData:
    MINIO_ENDPOINT: ENC[AES256_GCM,data:khtrTNef3RkmVWq5ksok1SPcC2lBLi9a9MVmdEC5Kpm4+g==,iv:vFzan6KKiIO40E7I9bIvSzbyba3IaftwBjfXlCzSrwE=,tag:FiLMWe67nkXNKuA6Ry7i3g==,type:str]
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:akzh8uQ=,iv:ffXMq3YY3ACjQWa0DIznNda64s7UD+uTTrOmDb5m4w0=,tag:WFYkWigBvKgNzRUQ6kXaog==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:N2IanjcTkqPuN6i5X9t2EUDnlk1VZj7SMyR9ogSMCRg=,iv:d5+74iVhe4r/uWPX/6iB2Nds9LOuZpK44zRZOayu8Gk=,tag:V3isLwYSgk+zUw4VHajacg==,type:str]
    LAKEFS_ENDPOINT: ENC[AES256_GCM,data:3bNWcOcPsFEouDF6mW6G97OAPUDslPCriErYUT6gcoPtOVeceJPRxjE5aw==,iv:oJlAJaWDdq/6jy7P95AsNCjJMVa3D0Iulfeck733TSI=,tag:qDmjwdgza9B3lDaW364ANA==,type:str]
    LAKEFS_ACCESS_KEY_ID: ENC[AES256_GCM,data:rMeuDbdK3Hid23HT2MEmH34y+hI=,iv:YA2nLdPXne6vlyzUnE5QYp4sm1Fbamy6HLMqrsg4iwk=,tag:0aPPTVEO1Al46KiqceZyiw==,type:str]
    LAKEFS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Mgvb4QE4tVCiUyFfOMjXXmFyGC1FlJVyV0GYa/kDIi0WrDCRfjTf4UiuRhc=,iv:GDsz04Ci3AOBSSy3UZQYwauGTbku3WmT06QJoA5oav4=,tag:YtzfoS6txX9IocnIHQBexw==,type:str]
sops:
    age:
        - recipient: age18vt4yspgr9qtq30n6ty20l8jpxeu5drd38sl9kdlxqvggswtsdmsyeydck
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5V2V6Q0dpNVkrS0U3Mm90
            Z3cxYzFmQTMvb29oaHQyQlo4MzlKUzhhTXo0CmJEbXFpcjA1MkR1MGpDQ2tJT05G
            VWtuOFdQMmZNRCtGdWdtWmExTG1KREEKLS0tIDFmajB1QnoxdWdXVlZHL05PSjFt
            T05ZU2MrRWJUL2VMMzduN2t0UXNhL28KxIPNnqCVRV4YXGB0ssh2ubPJ7UHW/mvA
            IpnJN+G35HuqeJ7PB34SMFJNncL4UkcZ/k5P4HCfH5jeucEOgzqFRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T13:52:25Z"
    mac: ENC[AES256_GCM,data:zjFMJZvqec3IyYrUea+Yllrup/AM5KOKYcHIgZ2/YJ+9lDwVRmzmBXIKgQhI7CoF3Htt3dn9+uT2ZBdNErF+UaYv8hiZgiMZytMvNc06bbB89GRe9hJpKHMjajDy2Dj+m5G0uKGBh+tRJGQBmsRU92J5cXQGcsIU4nSTu7kWEEY=,iv:EAMLOncutNIX/3K4k3rrkwG3FtXUgTINI2b/svQDgZM=,tag:Rds62S30PYWzj2wsfFA6Vw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
