apiVersion: ENC[AES256_GCM,data:IOU=,iv:rXaoD3EO6FM7ryw968oAUmKSDkKJT36dUvP0sWjG3NI=,tag:PgEIx3VBWmB5fcB+wLSpxA==,type:str]
kind: ENC[AES256_GCM,data:4USOh0uq,iv:GxZHCMAfBRpmIt/R1JqGt99VQmXAHJDXlv988qIYlTk=,tag:n90h7zaWCd+WVxXHEEK68A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:5JSwi+ROAUMXEIW5/v7VFEg=,iv:zvBCt0f6fjsFMsIZEzueX7MdRK58mssTlbJLt6CRkvE=,tag:qTG6FA+2Nryk+bzyHdSjpw==,type:str]
    namespace: ENC[AES256_GCM,data:nVO+ee0=,iv:FEoWQ5tExzTYH1A5b363Q1/ZOpOSXVlU4fOD5lPtXVI=,tag:7osJpa2OIwoiwK1X0sGjUQ==,type:str]
type: ENC[AES256_GCM,data:aV7A5ADj,iv:lduqMITHtOg6p2y2wR4YXlxo90r5tH/SZf8JCPrnpDI=,tag:Yh5VqK5OmBKuOiorChyfuw==,type:str]
stringData:
    rootUser: ENC[AES256_GCM,data:1IGeGSg=,iv:ScV6XP+ZNr9DL4aemA2g6mutP+GSlmE+7uIyG/o7hnE=,tag:tyrmU+eTAij9H1ICUok54g==,type:str]
    rootPassword: ENC[AES256_GCM,data:vSqy3RDdxbBFW7UEnvGje2fqVAKzaCDxKOUS3yOWEzY=,iv:SmzVrfGhm6COKx4Ge66mDjcI0FyIITn6WOaxByEXUmQ=,tag:IBtGr4UEbvkqkcX2uWCD8g==,type:str]
sops:
    age:
        - recipient: age18vt4yspgr9qtq30n6ty20l8jpxeu5drd38sl9kdlxqvggswtsdmsyeydck
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1d2Y3K2ZZd24rTEorQzJ4
            eGlGazNxaEZDN3JFQy9jT0JUV2pERzcxRVZnCml4T3BGMzFSVGhCRk9wZ1dSSFQv
            Q0lQN05aemlPTWJCTmJXWDVuNjB6TmcKLS0tIHRHamdQRUVOSk1kK3kxOUpMNXVw
            elE0SW50VDg0L1hiOHd0YVRjZnpaSnMKb5Maqr5OliWihBMiBipTT9MJ1mU2nSkm
            KCrjCcXQxq7qFKFIUh6/p4PGYiETUBsKWsG5E//phPyJxdboc5mLfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T12:00:40Z"
    mac: ENC[AES256_GCM,data:PTO74opeFNXf2IkBhlGHLh1/XKckHvSzoZi1FFUNBlQz3kus8iVr4/AbXKksk3qeUp6+lbxNVchMNk5NBBpT1YMRtRa1SpPjrQf3UZKZuQvfGJ1LWlMhGsgEfRU9g/MbFMnNYIoIAUaxSDkZqVC4Ybxutfy/PcjjZtjFhe9SlUk=,iv:gBjfBWniSIopkbWpNyysrr7MGY0SzVwYlJOjYvh/sIs=,tag:njBWy6TKuj3cs+0jmI/VBg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
