apiVersion: ENC[AES256_GCM,data:5ew=,iv:u6qKA69HlB/hCePkm6xSLKG84BaNTiznajXJFKgl8H0=,tag:eHFuFrBoOo1DqUussySnew==,type:str]
kind: ENC[AES256_GCM,data:RQMdXIKL,iv:NqbDCeEN7KXCBfinBe5R+XNb3GR/FGCGKBdcYLkfGYs=,tag:LsdzaDZy2Rlk/WSwLJ3apg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:lUDs/yK/PEncLTysYCvvuQ==,iv:9KRms1LsE6yN5WuQflWn9yzvpGIr3zez1aeocyV09e4=,tag:r1+SIBmki1P7sIZM4FAPqg==,type:str]
    namespace: ENC[AES256_GCM,data:tLhI5IKE,iv:PjdW4Cc6WHzQbWQ1LLm3vLKlH4TH7NkKrM8BErbRRWw=,tag:b0qHuXJoOjXLlb4YGnLgfQ==,type:str]
    labels:
        argocd.argoproj.io/secret-type: ENC[AES256_GCM,data:4mtDdJFMg/Xq5w==,iv:YGwA8zmgLXTfmwlsOp2o+Z89Z13idYcfUX7pGFYXbUs=,tag:8dxZGkOAtO5ey49/H/e9Sw==,type:str]
type: ENC[AES256_GCM,data:BkK1vuYC,iv:48WvP5CErqidws3x010Or+wZGiUFVJd1AOIukzr73jM=,tag:jImzMg/KtdavfN6pus3UPg==,type:str]
stringData:
    type: ENC[AES256_GCM,data:njvp,iv:owGg32ntKCHuu21MVfKcsQwCxFpqtyCCM0Ln8S8Co7s=,tag:HIDgVP6o1kNEp3fOxJzAUQ==,type:str]
    url: ENC[AES256_GCM,data:GCjDEJ9gsLWOnK0ohRytQDhr6c6G/YBYHB9wyeULW5+HXNL19aGMYKjlDUeqSB3W,iv:/8PmdKTdKCLUJcD3dausk4ReDXFVyC2pVUB+1t/Nwrs=,tag:gXXqFpri2Qm1loFWBJRKsg==,type:str]
    username: ENC[AES256_GCM,data:jaal,iv:rLBLQsdLjfDXptlXtawVIoVThxLxpSApYdbrrgEIX/s=,tag:BQ0t7W3zZrNIocETpBEe6Q==,type:str]
    password: ENC[AES256_GCM,data:G862d3l8NLytfH8Knl/NHiHzts6oWmYwTCIPProWnHn1jpoEy/sHGA==,iv:eQ7AZmXW6f24sB6tQJ+ZMFqIW9Wl+j3Pnn2zFHlVhic=,tag:qOlB7OIPOnSaWViZ+v1fvg==,type:str]
sops:
    age:
        - recipient: age18vt4yspgr9qtq30n6ty20l8jpxeu5drd38sl9kdlxqvggswtsdmsyeydck
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIQW1nRjVTcFg1QTM2UWtn
            YUptTGswbURMVkVBMXZTRHY4aW9BK1o2Ym5JCmQrSEdIUHEyUVRvSDU5VXZkOFFk
            bHkvMjB6T3VYR0FWY1lvclozL09MSGMKLS0tIG13OHpUam1Ud292YXhrT00ySFl1
            NGVyY2UvakdsK2lySmx1cFZ1OG92ZEkKa4oUAjCcrc/LaoTROzdvpLT7fr5h/lIo
            SS8JPjIl+OCH84P/xQhRDm0imvkfVMvNFIkKKqzxTep/IakB8yELVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T13:52:25Z"
    mac: ENC[AES256_GCM,data:tLInzIV3wJ13WSDYoTQFVjMoLgyL9gj70MyL9p/3KrczDQT1Vs+IQIziuRTCCLD6ZpIs+02apNEfUiCDpDwTJabbm2s8jOWysCcAFhEmTQZcfanBCg5jE3L3e7uAyv1WE2gH/O1QZDep9Ye7K37cqaRY+fHhiiVxA5k9f4xSdHY=,iv:24w4gCbYGdf4oU8dnacsUso+D0wujgdUFUj/pbZ3M+4=,tag:6zFPtVTN357jGvZPdXKD+g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
