{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
    {{- include "nvidia-nim-embedding.labels" . | nindent 4 }}
{{- end }}
