apiVersion: ENC[AES256_GCM,data:zzg=,iv:97Ui+X2iHJ0Y42pX59zqtOwjQxLnxhgGtdL33gml2D4=,tag:r6Z7qYKo7AEogPolMSIgfQ==,type:str]
kind: ENC[AES256_GCM,data:16623r/Z,iv:iD+r9A6yEYaxqns/0vMhdHMCXH3ieaEq+2BUo1RVBJM=,tag:fKboxN/9/A9Aejmcz4duRA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:vAhq3P68SnBAsUizXGcFRmAn,iv:hrvhO886Sm9acw6wrs64W6rcllYIvjvcRiwZPv4GFDA=,tag:5zUBCLAUEavrm61XT+HGBQ==,type:str]
    namespace: ENC[AES256_GCM,data:pqn+lRAL,iv:SbdOk+R+0cJ7YWO+3GWD4VoHd9AOoGDcDYA3TY5bvPc=,tag:12nXXDCEIp60eFGUuxdXbg==,type:str]
type: ENC[AES256_GCM,data:jrKR3m5+,iv:dwb3ik5+E7FFvmzKPYW53/sbWyzHP0AEr245LeY+4xE=,tag:qzuVYLneprM70yy/WmWx9Q==,type:str]
stringData:
    access-key-id: ENC[AES256_GCM,data:99UleVVOG03ALDWbb55V48KNrBc=,iv:VnCrcUZ468cDw+Y4HGRc6czfDONDagdUVsgBDid9ets=,tag:WmrcZ5lE4VqPiOqIokt8JA==,type:str]
    secret-access-key: ENC[AES256_GCM,data:uHKAss/PY6coQ85KzBc9PHzTydtgpGSK58cz5/48n6jTNunwqHyw63BD5LU=,iv:Lbt7AlcEGiDOEfTz8l4OQ48TkCFY7b8peBZAn5PbHhU=,tag:N/yEpLrwj4fOrbYhpyeNHA==,type:str]
    minio-access-key: ENC[AES256_GCM,data:nHt+Xa8=,iv:BmFQtQbyeMVYS/Wy7zq//iaaNW1lGNOQEetAbz45mf8=,tag:mdEi4dT49DAuk2ZTHMZBIg==,type:str]
    minio-secret-key: ENC[AES256_GCM,data:XzVz67NwpkLgSAiqTi5w1wUSgSTmguze4hHayHcHhPM=,iv:nxBWM4PENcrv/zAppmrA3Ts/xLrJGLit5YgH0/2bLyE=,tag:xkHqyiKfqu9wl+WIAvrs9g==,type:str]
    #ENC[AES256_GCM,data:Y9nKFxwsZzRoK6TLbjggru79e0jq6e2xvmFxlWotjD2KvZJ/iAdVlYwopfgTzaDQ6A==,iv:q7tAUJ6SRLVhDdvyJ2/Osudi/DCbzLunVJFZn3Fm280=,tag:4jUPZrk3TjmVCw+V9Xo2WA==,type:comment]
    auth-encrypt-secret-key: ENC[AES256_GCM,data:Bz2TvhBoQAIazFRqho5oXLyx5Oob5BZy4hH7FBJES4Y3VG8L/U8fPbnANawYyZve+MnqlGKPKeuSxHjWcxtXLg==,iv:IQaDRg8Td6s97q+qhbZa+sae7/hrIHh6Te2GUxtkouU=,tag:3NS76CDY6kYXOVal6K2J3g==,type:str]
sops:
    age:
        - recipient: age18vt4yspgr9qtq30n6ty20l8jpxeu5drd38sl9kdlxqvggswtsdmsyeydck
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjd051eVRPRHlsZ2x5MmFF
            T3V3RmZZZlpDYWFUTk9qTEgvZ1lJZVdJb0NBCmFVZmQ3RFZhMDJRZTdUOTBPL3B3
            ZDVyL3RoaE80VGFubmFzQWJ0Umx2QVUKLS0tIERwNGtDUzdOZlRaQTZ6OVArWlQ5
            RHIwR29Vc0UyOTlYN1lqWGpxWkk1bXcKMEI4S0U34SWBZAoyryDZ5cgI2qXXrM4N
            uPv2vXa8GIY52Do8mPA8o/ShGkLkUXufQpRzwMQZo88GHHnzZ3Vtyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T13:52:25Z"
    mac: ENC[AES256_GCM,data:GTwnynC0y9VEe3UR7GUZM07B1Xr5GH68O5zTV0DtJd39DWGeOYr/UT4XlJzWwrN/ykGjpO1vlFhDiK/2iAc6EHXWdXATFcfA78jXXiLCLT6bDcH2LChBdzQfAyWLAopexFwj2zS/gUGsa/r9G28rTk5dlITMQYb+7PGR91860/k=,iv:l6M25kcjEEfkHi/CnrljAM5bKrhNxqg2seWJH3+zfKs=,tag:gJ7012R8Eck2yVxyQ6irIQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
