apiVersion: v1
kind: Service
metadata:
  name: safe-synth
  labels:
    app: safe-synth
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: safe-synth
