apiVersion: ENC[AES256_GCM,data:yDA=,iv:N/ol9uoTgMecJn6B0uqkHrWAyknzmWcaAzf6USugtWc=,tag:bUriWWkc1PM+pqevKhATQQ==,type:str]
kind: ENC[AES256_GCM,data:ViibSA2w,iv:6UOD9RFQi543k/q/U1UpYRZecmsz+F+D3XdL7RKAy1Y=,tag:vy2s/QeNI5uepZCY17F0KQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:5R3MCicjAM6ukwIBg2l/ygky+rljjA==,iv:h46GfM6HcKJYoR+C5T2zqvs9CmzRs3jwQN47m46TXgI=,tag:p8exBRMtkEK4QqyXHtcY/g==,type:str]
    namespace: ENC[AES256_GCM,data:ucvoc982Rvyhuw==,iv:ew5AVMDWNTWzxls8RD2x1ytvyQkeVgByJ4WmtvFDCa4=,tag:SvpyfqReJswTN5Y6biZ15g==,type:str]
type: ENC[AES256_GCM,data:OwPly4kM,iv:UoN6Re+kv6/v4KYqQn3aI/zjZOTrNRDEkOScwd4SC+g=,tag:FZf0fyGr2gZa/ppdZ5vARg==,type:str]
stringData:
    MINIO_ENDPOINT: ENC[AES256_GCM,data:wMBNbQUj2hetyRBtVr0uyCKXmfI/1zUBwMdni44NtcUHVQ==,iv:1TQT8iDek3weWX5aaOVlmViK+Pl36JqqnS5/v+HItEE=,tag:na1nT3O688gbBR54DakfjA==,type:str]
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:eglZ5WE=,iv:Xs7lEbJPpGfq8yrGAY5Wf6OxRbEqYIvsGSa7dkXWbSE=,tag:BgbWIcP3cAd7gzVxPvFobQ==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:algqRCkoY804jlyrf+Xb4Op64i+VOnfqA7OsB84YF5o=,iv:HYt4Eeecl8fXxhI+HoXKQwj2+buNjheYr2GN4TGzzsg=,tag:chasysAlyJOf4x6a1N6dAg==,type:str]
    LAKEFS_ENDPOINT: ENC[AES256_GCM,data:LIHW17XV+9qQbuXEMpg0uKBFH/cJVUQwL9/rc6pmVJ7LhfcBygAqkZ8KdQ==,iv:7QTaJolhn5GJkrb9+tE6wWEb1nLnpSuaMrwGIjSYCdA=,tag:9nBN5SUs2JJ4YjRfxNGuHQ==,type:str]
    LAKEFS_ACCESS_KEY_ID: ENC[AES256_GCM,data:B1tK51TY32Ute9ChKkjuQ8cnR2M=,iv:R9cjOeBmZCJ9cxK05XiEqRfLH1hL3B3NHNfFwvUnaOo=,tag:JW157Q0Fl/N/2nn6IPS5iA==,type:str]
    LAKEFS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:9uGcm02e6NesLMWYmgA0pipIjlXwmnakR3xL56AlnGmS6dMIPvNIZbwHRps=,iv:XLPj5eRtp+j2nle2Gj3ZF/gdt/1/eobkC38DeEjtJx0=,tag:BgDmO9Fp2sPU7bBK8VVM2g==,type:str]
sops:
    age:
        - recipient: age18vt4yspgr9qtq30n6ty20l8jpxeu5drd38sl9kdlxqvggswtsdmsyeydck
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZcFhYRGRzZ3RjLzhONFZm
            a3BIV204dkZiUUhaKzE1anJKa1cyRWRubjJnCk53RDhoUDErT1lZMlR2MWM0YUNo
            eDUzZ1daRkxrTTdCZDZoVXBQL3Y5VVEKLS0tIE5zYnIzeUxWQnlSS1hZTy9kaC8z
            WDRFSEpOOSs1UTNEQWpzL2dnY0x1Z1kK2V8Po8+1xw59p86f9oCnGXQg6WpNaYNN
            Xe5jT3yYDNFgGDAkLegtpaHtJRpyEDV6DGb0PnXg1Sq9Nbta1xw9Qg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-22T09:21:05Z"
    mac: ENC[AES256_GCM,data:UUGtRF+Vt4zbomI1VJ5Cc0rNACf5cS3uL/rEOqh4774CgCDDbwvXSYjj8dnGjeDkzbNffbY8dL/gBlsRP/4cxOTJauu9Fa44/aCGbAoIsNLQjdeqdnqnE9tJydOgo54MHUvUDJTtC92wupnGDoWJGBiE8VB39BDHpcGXZpar6DM=,iv:JMV2TFJc/b1elKfcz7SS46zzlhjcSbgVPjecnPxpWLk=,tag:1CwTODbhDu1q+4V6PFH7oQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
