apiVersion: v1
kind: ConfigMap
metadata:
  name: dagster-workspace
  labels:
    app: dagster
data:
  workspace.yaml: |
    load_from:
      - grpc_server:
          host: dagster-user-code
          port: 3030
          location_name: "brev-user-code"
