#ENC[AES256_GCM,data:ow9WvRPukuvuo2Usy1c0A5v/Ydko0yAG/MBmYm66Z43YXvQ79mIPQU5lFp/0dglAHWjW6d4Qk38zhkfZqILOL9HbiQ==,iv:fw2Jh30GM3cd2qvgrMJf7I2GfKwve6bljRVq3akkTEo=,tag:+DiFTIx3TZAtNeH4pKpz3Q==,type:comment]
#ENC[AES256_GCM,data:7yb+THlPiC6U1Dcwbc7vgzwoB+Tm0/uqi+LQ9GXiOZgFCghz62BHXR5px8h7x1NZVbTXHt8EQuRqkhlpgzz0tmfCDYRk,iv:qFMgIjIdC426jamh66y4jnsKLunWZO7JaM1DFtKiz+A=,tag:MfUH8SeQU4W6rbVugriaQQ==,type:comment]
#
#ENC[AES256_GCM,data:587eYQhrcJBN9ds/EExv9ERivMmDfoMW6TPMeuHCS0hjledoMrTe6bnTFhPbowT8lDkZWXGy,iv:DIJdZpbTkoKd8cFPKyL7CL41YH55UbLZx8kRBwhKCic=,tag:sG9sA3c6n1dtdeiz8yn15w==,type:comment]
#ENC[AES256_GCM,data:RPcExOsLtYxOdeUxPC+abXlsx8midxSR+MIgOQYZJ1xqte2NksMQE8ZHe+W759S74LGURdZwychEcT1xwiFF8xJ0IIk6p6T736bD2L0sVKXVgQ==,iv:YlRbll7sZ6fKzEfEIh6ewpvLcaf2+zeIUZoYWe1vjgE=,tag:90MvkpPW9NRV4uNz5gnJgA==,type:comment]
#ENC[AES256_GCM,data:/7Ck8WjH4uw+HPnWIRUKoRF/Rxsd7kSC5EzQUK8C2stYaBm1TV0oNhAtqy0lRmbcgbN4JpDpyZp1k3ZnSEs9IIr67/mVPnuXh6devSQmYIfAt2NGUBJdmWjrUGxJKbsCU/IBgg==,iv:gPQ5pjlxf8qJSX2nToz2Zv/KtFbnQyutRjkM1ye1RCs=,tag:/oQoQ53ZF/OXw+2zIkuhJw==,type:comment]
#ENC[AES256_GCM,data:vbAWzXdI75mNeupEzTOZlSRjuBw8snkhRfBbbZUUnl2ph/Z6IQ==,iv:vreuB0EaHb3TKO+iaLmNM2GFZFGOqwj4SDOpubNYcE8=,tag:KOclWXT6W7dY0ZJExmytww==,type:comment]
apiVersion: ENC[AES256_GCM,data:lNg=,iv:AhaMZLJepKdJ7rtnMNareov66OOot13qwJuFAHg+Ibg=,tag:HmcC69TL2WH3MHj2xW4yYA==,type:str]
kind: ENC[AES256_GCM,data:2VR35KXk,iv:vBhQkfXZ6kf0vnEahUQeEPGaJuDEQx3MULF+9ly8EtE=,tag:dCPJe+IJluv7jB6b/M/HDg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:J++LHsH0fY9uKLAJ76y1,iv:qh+vfL57Fm+v+twydJuePgjzLGvmHSLldlXTzZ9ZuQY=,tag:MMEN0Auldo7MSLUUCSutHA==,type:str]
    namespace: ENC[AES256_GCM,data:OpfuoXihQQ==,iv:1ssUtyzxBFz/4BcGP5sfH8XxZzMeoaLctg/elXHZe0w=,tag:yikvPtGI3UxzceyMd9XAzg==,type:str]
    labels:
        app: ENC[AES256_GCM,data:Y5jaITSWEw==,iv:FvEqMeu535d53MHWvDBeer/vWIYllFFmiBUFD1gg4jc=,tag:+dX08Cw8wRPQdP1fl5TDyQ==,type:str]
        component: ENC[AES256_GCM,data:8ldYk/481et2bsITTcq9,iv:2mzvGsbdxDdttpoXRhmQcBooc9vSjBpuL/Ndu4Lp8aM=,tag:kn7aUrF266BL78n6/EtWPA==,type:str]
type: ENC[AES256_GCM,data:dRGVYFMT,iv:dxcb6ctfGalPwYGfR/1XmuxIDKSWQbWLBc9SLvGww6k=,tag:R7nVRLY/Zqfssyf12Ele/g==,type:str]
stringData:
    NDS_TOKEN: ENC[AES256_GCM,data:rgHIc7UTVHZdHiZ+JrCyjvciKCg4TuY+kqKecHu2aXZsM8Lyz+ol6Q==,iv:DKIiyznXn1Cru+3t/vvYvzmQt/CaxPCuGf2HVoHXJAk=,tag:3uEMSg+gQQ2Oki5Kr4VCkg==,type:str]
sops:
    age:
        - recipient: age18vt4yspgr9qtq30n6ty20l8jpxeu5drd38sl9kdlxqvggswtsdmsyeydck
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBMVBCczh3TDRoZG5jZWd4
            ZGRFMStCZ2x1QmdtNS9IeHpJT3d5SWV5RTJZCkZodUdXa1pickNVY0dEMUhXNXJt
            VmdsZjMraEM1N2Q5MkxQRnhmVTdPbGcKLS0tIEQ1UzNXQUJJNEdIZWRXeFpFSVB5
            QlFyOXhsWVBSMTdYUUE0UkQ0R0JKUmMK1DxBzcEbCur/YWJX+qklukFcBdfe895d
            z6iAtu6mJC5cCxMFPQqh1P7zlOosElHZ+OTBAajcePs4lxCd7t7GWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T10:25:44Z"
    mac: ENC[AES256_GCM,data:RGBBoRkpzdyj6P86kYXdrzZxxAbLaVIY0bIBRe+5P1nhWECTuOE4ELyRfZkjdK4G055B91m8NklUwd6MFSkKaPVZ2wKIr7RBm74jnZ7ovE4JW2iStUplcBWjXZpZYTgnutVPXpul1YmOXiKygZDfOGONvLtcfaJH4R3SOo9S3ro=,iv:NVhx9QWM14/pGc9YZsgP5rvuGZmZ0N0J96RIK6aFoo0=,tag:7Q8nfkMEoB2l5DOZkC+ZFw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
