apiVersion: ENC[AES256_GCM,data:B1A=,iv:DHIfx6VFqoKxXisAfyrSsYCPuFIBzIpzTDvosS9kWeU=,tag:Mewh6uKfw2Qzd/A6f69Lug==,type:str]
kind: ENC[AES256_GCM,data:a4GD1066,iv:yewqmc0upMT1QFVRclBveuiHGbWRPo/gun1ucjENUjk=,tag:7l5iWLRPq48T3ENecAgBqw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:RHupmD1MYIaIKEOYdsfkiKOyCg==,iv:xpt1h4DTet8xRVreqvo9Qt4V6zp7U39L4iLul2Ht7aI=,tag:v9nDBp5U8z2ML78YqghvMA==,type:str]
    namespace: ENC[AES256_GCM,data:HUQ0rugzSw==,iv:7D2OtY6EE6P/r3ivioiOjKDtvmoekCh4bfPN06bbeSA=,tag:bv9WrXaXI1RBMtlPJFH9lw==,type:str]
type: ENC[AES256_GCM,data:eUNkZaQW,iv:ZN1d4R6mb3GBaCFmU0mCTho8H2fhbmfSVBoLLyaxdt0=,tag:6oKYVd8VC83G2Wkdhrno0A==,type:str]
stringData:
    MINIO_ENDPOINT: ENC[AES256_GCM,data:MVwSSwLrI3JaB4MtPGjbRhCcG3A48ib+zMIQIZtl6QuLyg==,iv:PzqwHVHEs6i1X44UkvIYNOO4x+YIhUsOUgd8v7DpD1U=,tag:lgH60iPDs1bHTyn3koBSXg==,type:str]
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:ddqh9cc=,iv:HOq9e6IyPVnOjyaeVjlijsc/08kz6M0TPMWC548HnFo=,tag:eE9kSBV31XY4ka0CdOPQIw==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:qmunS4E4xjY4nGX8KwUcKQpTfHyZt/mQY6T9jE08fe4=,iv:IS+nt1EQZwOyG/S3bK++wF4lQJjwZtLyL3NqNowGgAI=,tag:vYDEsKaPdqO3mD39TelxjQ==,type:str]
    LAKEFS_ENDPOINT: ENC[AES256_GCM,data:T8oXv1LQlRLew2Zli596q/ymtD+bHN3umo+zlZANal0RFMaeHEF7DJw8NQ==,iv:1+RDghwRlBEFKR8orTH6hcGBhqD/+mBwQ0UO6CK9rXw=,tag:WUVsZW5/EpwB+ZbWANxzCg==,type:str]
    LAKEFS_ACCESS_KEY_ID: ENC[AES256_GCM,data:e2hO6qY3waTaabc58aop3QbpRUA=,iv:0k9wG3W3S++lABkFrUKJ43q+/San9nOU/8fkZ+kAFwc=,tag:yTTfeJ1XmWx2W5KN+6fxMg==,type:str]
    LAKEFS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:45r73ZTdMZLn8ou+QnB24Z36NGcONl2Nlh8lT/N9qsopAnRBTCd53fPB/es=,iv:wwyaHFWBiLqbWgEuTGO1YxCHJeaIxXyaDN4eBIqxwvY=,tag:vvcombGvUTTc2u12JaOoWg==,type:str]
    NIM_ENDPOINT: ENC[AES256_GCM,data:cTjl1YJr73D0us+u6e7Rv7zXjDmwWTb7AThLlyWT4dLEUZf464k07Zcy1BglIkw=,iv:2NexZrQuUjt0YZq6S4Kon1leoU83kVaNLcRMCUs8Wyo=,tag:ro4kwvAi5cl8o8MSiebzfg==,type:str]
    NGC_API_KEY: ENC[AES256_GCM,data:Z/5hspkuhz80Rnc/ZFXWuJIHJEoaSklqrmHIGbJCu5N0PAcM1SvTbce66swGHP+sRozkDK9hZ5A/+37zOCl54BWXIQHiug==,iv:gNogWnOd2AV587QrXM3JYRTDz7HcftYbLBmVKGenq5M=,tag:6EeVcvGh0WdyQKsUxgN+aw==,type:str]
sops:
    age:
        - recipient: age18vt4yspgr9qtq30n6ty20l8jpxeu5drd38sl9kdlxqvggswtsdmsyeydck
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFSzNRdU02YWJOUE5kcUVZ
            SkJRQVYvS1lGMENCMjlmNlB1cmQ4UVU3eFd3CklYNWdFU3EwUkxZMzkyRE9VbXdw
            WVNWcFc2cWdmeVhISU9RYnRRRjBkT0EKLS0tIHdTeGZWNzN6Tzd4VmtaWmJLNGNo
            alVkK0VqbWI5TUhQbm1zMlJxSlZwRTQK4AxUlypaxsIprrZFVMoFaIp33e0zG8PS
            rva6tJn7Z1nz3YIorpBAo8ea7QTo8sK6tpDXOSPIt7nAJTVBz4ku5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T13:52:25Z"
    mac: ENC[AES256_GCM,data:r6Kgbk+G+rR31R4bAh/jPXVB97XE99AAV7CeXmqEgiwRxdrqNHBQAbp7Hcvs1nxdRa1JoESRNhwL1iMbsGNRXBpUZEjMArSVVjfa5fHg+E3nokq34StRQ1nuZWRphKxLNhTtFnLgdXJNKSwWu+3wB5RtRqMo77kfAG/WxR9YxVc=,iv:in+ukRsN848Z9ohNahK0d4yhFLvcdUz5o9U/ASw4kM4=,tag:Kw1m33BxhH2ivQaW7306MQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
